version: 2.0
jobs:
  deploy:
    docker:
      - image: nobuhito/gae-go-alpine
    steps:
      - checkout
      - run:
          name: Deploy to App Engine
          command: |
            echo $GCP_SERVICE_KEY | base64 -d > $HOME/.secret-key.json
            gcloud auth activate-service-account --key-file ${HOME}/.secret-key.json
            gcloud config set project $GCP_PROJECT_ID
            python /google-cloud-sdk/platform/google_appengine/appcfg.py --no_cookies --application=$GCP_PROJECT_ID --version=$(echo $CIRCLE_BRANCH | sed "s/\//\-/g") --oauth2_access_token $(gcloud auth print-access-token) update ./app/app.yaml
workflows:
  version: 2
  deploy:
    jobs:
      - deploy
